services:
  server:
    image: "ortussolutions/commandbox:lucee5"
    container_name: luceeServer
    environment:
      - cfconfig_adminPassword=admin # set the admin page password
      - BOX_SERVER_PROFILE=development # needed to start in development and enable admin
    ports:
      - 8080:8080
    volumes:
      - ./:/app