services:
  server:
    image: "ortussolutions/commandbox:lucee5"
    container_name: luceeServer
    environment:
      - cfconfig_adminPassword=admin # set the admin page password
      - BOX_SERVER_PROFILE=development # needed to start in development and enable admin
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  # trying to automate npm run watch - does not work - error missing rollup dependency
  # vite:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.vite
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - server