services:
  server:
    image: "ortussolutions/commandbox:lucee5"
    container_name: luceeServer
    environment:
      - cfconfig_adminPassword=admin # set the admin page password
      - BOX_SERVER_PROFILE=development # needed to start in development and enable admin
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql:8.4
    restart: always
    environment:
      - MYSQL_DATABASE=appdb  
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d